# Generated by Django 4.1.5 on 2024-08-25 09:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomPermittedSSOUsers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sso_username", models.CharField(max_length=255, unique=True)),
                ("override_project_permission", models.BooleanField(default=False)),
                ("override_office_permission", models.BooleanField(default=False)),
                ("domain_status", models.BooleanField(default=False)),
                (
                    "date_created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
