# Generated by Django 4.1.5 on 2024-08-27 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brac_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="custompermittedssousers",
            name="sso_username",
            field=models.BigIntegerField(unique=True),
        ),
    ]
